// <auto-generated />
namespace Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class additemminqnt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(additemminqnt));
        
        string IMigrationMetadata.Id
        {
            get { return "202102251506246_add item min qnt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
