// <auto-generated />
namespace Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_doc_number_in_returns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_doc_number_in_returns));
        
        string IMigrationMetadata.Id
        {
            get { return "202109081045353_added_doc_number_in_returns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
