// <auto-generated />
namespace Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202102160929410_update-Models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
