// <auto-generated />
namespace Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class madepurchaseapprovalanddemandapprovalnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madepurchaseapprovalanddemandapprovalnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202109071240218_made-purchase approval and demand approval nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
