// <auto-generated />
namespace Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update4Database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update4Database));
        
        string IMigrationMetadata.Id
        {
            get { return "202102011213168_update4-Database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
